### ISSUE TITLE
Low mAP on the market1501 dataset

### ISSUE THREAD

**Issue by willard-yuan** [CoinCheung/triplet-reid-pytorch#1]
Hi CoinCheung,

Thank you for you code. I have tested it on the market1501 dataset, the result is lower than the readme result:

```
mAP is: 0.525827546826, cmc is: [0.7185273]
```

Can you tell the what's wrong with it?

**Comment by stoneyang** [comment]
Hi, @willard-yuan 

Have you solved your problem in this post?

I've trained according to `README.md`, and what I got after evaluation is: 
```
mAP is: 0.7140680399831403, cmc is: [0.8554038]
```

**Comment by stoneyang** [comment]
> Hi, @willard-yuan
> 
> Have you solved your problem in this post?
> 
> I've trained according to `README.md`, and what I got after evaluation is:
> 
> ```
> mAP is: 0.7140680399831403, cmc is: [0.8554038]
> ```

@CoinCheung Thanks for your code and could u plz give some suggestions?

**Comment by tuvovan** [comment]
hey did you find out why?
